-- Create database (adjust name if needed)
CREATE DATABASE IF NOT EXISTS `insurance_sms` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `insurance_sms`;

-- Tables
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `agency_code` VARCHAR(100) NOT NULL UNIQUE,
  `password_hash` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `policies` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `insurance_number` VARCHAR(191) NOT NULL,
  `customer_name` VARCHAR(191) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `notified` TINYINT(1) NOT NULL DEFAULT 0,
  `notified_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  UNIQUE KEY `unique_policy_cycle` (`insurance_number`, `end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sms_logs` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `policy_id` INT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `message` TEXT NOT NULL,
  `provider_message_id` VARCHAR(191) NULL,
  `status` VARCHAR(50) NOT NULL,
  `error` TEXT NULL,
  `created_at` DATETIME NOT NULL,
  CONSTRAINT `fk_sms_policy` FOREIGN KEY (`policy_id`) REFERENCES `policies`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed agency profile (code 549) with password 'test1234'
-- Hash generated by PHP password_hash('test1234', PASSWORD_DEFAULT)
INSERT INTO `users` (`agency_code`, `password_hash`, `created_at`)
VALUES ('549', '$2y$10$L3lB6WZ7C4b5F2xj8pJ2eOUQjV0z1yZg7hKMvO3o8JrG1B4sM5r7y', NOW())
ON DUPLICATE KEY UPDATE `agency_code` = VALUES(`agency_code`);